import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shopgen.settings")
django.setup()

from products.models import Category, Product


products = [
    {
        "external_id": 1,
        "title": "Wireless Headphones",
        "description": "Comfortable wireless headphones with clear sound and long battery life.",
        "price": 59.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 120,
    },
    {
        "external_id": 2,
        "title": "Gaming Keyboard",
        "description": "Mechanical gaming keyboard with RGB lighting and responsive keys.",
        "price": 79.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 210,
    },
    {
        "external_id": 3,
        "title": "Casual T Shirt",
        "description": "Comfortable casual cotton t shirt suitable for everyday wear.",
        "price": 19.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 95,
    },
    {
        "external_id": 4,
        "title": "Smart Watch",
        "description": "Smart watch with fitness tracking notifications and health monitoring features.",
        "price": 129.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 180,
    },
    {
        "external_id": 5,
        "title": "Backpack",
        "description": "Durable everyday backpack with multiple compartments.",
        "price": 39.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 150,
    },
    {
        "external_id": 6,
        "title": "Running Shoes",
        "description": "Lightweight running shoes designed for comfort and daily exercise.",
        "price": 89.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 230,
    },
    {
        "external_id": 7,
        "title": "Denim Jacket",
        "description": "Classic denim jacket suitable for casual outfits.",
        "price": 69.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 80,
    },
    {
        "external_id": 8,
        "title": "Bluetooth Speaker",
        "description": "Portable Bluetooth speaker with powerful sound and compact design.",
        "price": 49.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 175,
    },
    {
        "external_id": 9,
        "title": "Leather Wallet",
        "description": "Compact leather wallet with multiple card and cash compartments.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 110,
    },
    {
        "external_id": 10,
        "title": "Sports Shoes",
        "description": "Comfortable sports shoes designed for workouts and outdoor activities.",
        "price": 74.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 140,
    },
    {
        "external_id": 11,
        "title": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with precise tracking and quiet clicks.",
        "price": 24.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 165,
    },
    {
        "external_id": 12,
        "title": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand for a cleaner and more comfortable desk setup.",
        "price": 34.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 13,
        "title": "USB C Hub",
        "description": "Compact USB C hub with multiple ports for laptops and tablets.",
        "price": 32.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 118,
    },
    {
        "external_id": 14,
        "title": "Portable Power Bank",
        "description": "High capacity portable power bank with fast charging support.",
        "price": 44.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1609592424848-0a9c4f8e6c20?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 205,
    },
    {
        "external_id": 15,
        "title": "Instant Camera",
        "description": "Fun instant camera for quick photos with a retro inspired look.",
        "price": 99.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 188,
    },
    {
        "external_id": 16,
        "title": "Cotton Hoodie",
        "description": "Soft cotton hoodie with a relaxed fit for everyday comfort.",
        "price": 44.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 145,
    },
    {
        "external_id": 17,
        "title": "Slim Fit Jeans",
        "description": "Versatile slim fit jeans with stretch fabric for everyday wear.",
        "price": 54.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 170,
    },
    {
        "external_id": 18,
        "title": "Casual Polo Shirt",
        "description": "Classic polo shirt made from breathable fabric for smart casual outfits.",
        "price": 34.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1625910513413-5fc45c2f6c1d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 102,
    },
    {
        "external_id": 19,
        "title": "Summer Dress",
        "description": "Lightweight summer dress with a comfortable relaxed silhouette.",
        "price": 49.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 156,
    },
    {
        "external_id": 20,
        "title": "Oversized Sweatshirt",
        "description": "Cozy oversized sweatshirt for relaxed everyday styling.",
        "price": 39.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 126,
    },
    {
        "external_id": 21,
        "title": "Canvas Sneakers",
        "description": "Minimal canvas sneakers designed for everyday casual outfits.",
        "price": 49.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 214,
    },
    {
        "external_id": 22,
        "title": "Trail Hiking Shoes",
        "description": "Supportive hiking shoes with durable traction for outdoor adventures.",
        "price": 109.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 190,
    },
    {
        "external_id": 23,
        "title": "Classic Sneakers",
        "description": "Clean everyday sneakers with a timeless low profile design.",
        "price": 64.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 225,
    },
    {
        "external_id": 24,
        "title": "Slip On Shoes",
        "description": "Easy slip on shoes with cushioned support for daily use.",
        "price": 54.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1520256862855-398228c41684?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 92,
    },
    {
        "external_id": 25,
        "title": "Lightweight Trainers",
        "description": "Breathable trainers built for gym sessions and active routines.",
        "price": 84.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 160,
    },
    {
        "external_id": 26,
        "title": "Crossbody Bag",
        "description": "Compact crossbody bag with practical storage for daily essentials.",
        "price": 42.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 124,
    },
    {
        "external_id": 27,
        "title": "Travel Duffel Bag",
        "description": "Spacious duffel bag designed for weekend trips and short travel.",
        "price": 69.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 142,
    },
    {
        "external_id": 28,
        "title": "Aviator Sunglasses",
        "description": "Classic aviator sunglasses with a lightweight metal frame.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 98,
    },
    {
        "external_id": 29,
        "title": "Minimalist Watch",
        "description": "Clean minimalist watch with a simple dial and comfortable strap.",
        "price": 89.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 176,
    },
    {
        "external_id": 30,
        "title": "Travel Organizer",
        "description": "Compact travel organizer for cables documents and small essentials.",
        "price": 24.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553484771-047a44eee27b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 88,
    },
    {
        "external_id": 31,
        "title": "Ceramic Coffee Mug",
        "description": "Modern ceramic coffee mug with a comfortable handle and matte finish.",
        "price": 14.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 240,
    },
    {
        "external_id": 32,
        "title": "Stainless Water Bottle",
        "description": "Insulated stainless steel bottle that keeps drinks cool for hours.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 198,
    },
    {
        "external_id": 33,
        "title": "Desk Lamp",
        "description": "Modern desk lamp with adjustable lighting for work or study spaces.",
        "price": 36.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 133,
    },
    {
        "external_id": 34,
        "title": "Plant Pot Set",
        "description": "Set of simple indoor plant pots for desks shelves and windowsills.",
        "price": 22.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 104,
    },
    {
        "external_id": 35,
        "title": "Kitchen Storage Set",
        "description": "Reusable kitchen storage containers for keeping pantry ingredients organized.",
        "price": 31.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1583032015879-e5022cb8eeba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 76,
    },
    {
        "external_id": 36,
        "title": "Moisturizing Face Cream",
        "description": "Light daily face moisturizer designed to leave skin feeling soft and hydrated.",
        "price": 18.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 185,
    },
    {
        "external_id": 37,
        "title": "Hydrating Face Serum",
        "description": "Lightweight hydrating serum for a simple everyday skincare routine.",
        "price": 26.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 151,
    },
    {
        "external_id": 38,
        "title": "Aloe Vera Gel",
        "description": "Soothing aloe vera gel for a refreshing addition to daily skincare.",
        "price": 12.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 119,
    },
    {
        "external_id": 39,
        "title": "Lip Care Balm",
        "description": "Simple moisturizing lip balm for comfortable everyday lip care.",
        "price": 8.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1607602132700-068b8c6d1a73?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 83,
    },
    {
        "external_id": 40,
        "title": "Everyday Perfume",
        "description": "Fresh everyday fragrance with a clean and versatile scent profile.",
        "price": 39.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 172,
    },
    {
        "external_id": 41,
        "title": "Mechanical Pencil Set",
        "description": "Smooth mechanical pencils with refill leads for study and office work.",
        "price": 10.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 72,
    },
    {
        "external_id": 42,
        "title": "Daily Planner",
        "description": "Undated daily planner for organizing tasks goals and notes.",
        "price": 16.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 141,
    },
    {
        "external_id": 43,
        "title": "Notebook Set",
        "description": "Set of lined notebooks for class notes journaling and planning.",
        "price": 13.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 126,
    },
    {
        "external_id": 44,
        "title": "Desk Organizer",
        "description": "Compact desk organizer for pens cables notes and small accessories.",
        "price": 18.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 97,
    },
    {
        "external_id": 45,
        "title": "Premium Gel Pens",
        "description": "Smooth writing gel pens with quick drying ink for everyday writing.",
        "price": 11.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 108,
    },
    {
        "external_id": 46,
        "title": "Yoga Mat",
        "description": "Cushioned non slip yoga mat suitable for stretching yoga and home workouts.",
        "price": 29.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 215,
    },
    {
        "external_id": 47,
        "title": "Resistance Bands",
        "description": "Portable resistance bands for strength training and mobility exercises.",
        "price": 21.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 149,
    },
    {
        "external_id": 48,
        "title": "Adjustable Dumbbell",
        "description": "Space saving adjustable dumbbell for convenient strength workouts at home.",
        "price": 64.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 49,
        "title": "Fitness Jump Rope",
        "description": "Lightweight speed jump rope for cardio workouts and conditioning.",
        "price": 15.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1517963879433-6ad2b056d6f4?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 95,
    },
    {
        "external_id": 50,
        "title": "Foam Roller",
        "description": "Textured foam roller for warmups recovery and post workout mobility.",
        "price": 25.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 113,
    },


    {
        "external_id": 51,
        "title": "4K Smart TV",
        "description": "Ultra HD smart television with vivid colors and built in streaming apps.",
        "price": 399.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 245,
    },
    {
        "external_id": 52,
        "title": "Noise Cancelling Earbuds",
        "description": "Compact wireless earbuds with active noise cancellation and charging case.",
        "price": 79.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 320,
    },
    {
        "external_id": 53,
        "title": "Tablet 10 Inch",
        "description": "Slim tablet with a bright display for entertainment study and browsing.",
        "price": 189.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 178,
    },
    {
        "external_id": 54,
        "title": "Webcam Full HD",
        "description": "Full HD webcam with clear video for classes meetings and streaming.",
        "price": 54.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 114,
    },
    {
        "external_id": 55,
        "title": "Portable SSD",
        "description": "Fast compact solid state drive for reliable file storage and backups.",
        "price": 89.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.7,
        "rating_count": 267,
    },
    {
        "external_id": 56,
        "title": "Smartphone Tripod",
        "description": "Adjustable smartphone tripod for photography video calls and content creation.",
        "price": 28.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170315870-ef7c0b6b0e7b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 86,
    },
    {
        "external_id": 57,
        "title": "LED Desk Strip",
        "description": "Flexible LED light strip for adding ambient lighting to a desk setup.",
        "price": 19.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 137,
    },
    {
        "external_id": 58,
        "title": "Bluetooth Mechanical Keyboard",
        "description": "Wireless mechanical keyboard with tactile switches and a compact layout.",
        "price": 94.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 189,
    },
    {
        "external_id": 59,
        "title": "Action Camera",
        "description": "Compact action camera for travel sports and outdoor adventures.",
        "price": 149.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 154,
    },
    {
        "external_id": 60,
        "title": "Smart LED Bulb",
        "description": "WiFi enabled smart bulb with adjustable brightness and color settings.",
        "price": 15.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1550985543-f47c0f4c8e0d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 121,
    },
    {
        "external_id": 61,
        "title": "Formal Shirt",
        "description": "Crisp formal shirt designed for office wear presentations and events.",
        "price": 42.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 139,
    },
    {
        "external_id": 62,
        "title": "Chino Trousers",
        "description": "Versatile chino trousers with a clean fit for casual and smart outfits.",
        "price": 46.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 118,
    },
    {
        "external_id": 63,
        "title": "Flannel Shirt",
        "description": "Soft checked flannel shirt that works well for relaxed everyday outfits.",
        "price": 38.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 127,
    },
    {
        "external_id": 64,
        "title": "Zip Up Jacket",
        "description": "Lightweight zip up jacket for layering during cool weather.",
        "price": 59.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 105,
    },
    {
        "external_id": 65,
        "title": "Relaxed Cargo Pants",
        "description": "Comfortable cargo pants with multiple pockets and a relaxed fit.",
        "price": 52.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 143,
    },
    {
        "external_id": 66,
        "title": "Knit Sweater",
        "description": "Warm knit sweater with a soft texture for comfortable everyday layering.",
        "price": 48.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 67,
        "title": "Athletic Shorts",
        "description": "Lightweight athletic shorts with flexible fabric for workouts and running.",
        "price": 24.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1562886877-3c3e8f4c6f65?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 98,
    },
    {
        "external_id": 68,
        "title": "Linen Shirt",
        "description": "Breathable linen shirt suited for warm weather and relaxed occasions.",
        "price": 45.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 111,
    },
    {
        "external_id": 69,
        "title": "Classic Blazer",
        "description": "Tailored blazer that adds a polished look to formal and smart casual outfits.",
        "price": 99.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 174,
    },
    {
        "external_id": 70,
        "title": "Basic Tank Top",
        "description": "Soft lightweight tank top for casual outfits workouts and warm days.",
        "price": 17.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 84,
    },
    {
        "external_id": 71,
        "title": "Running Cap",
        "description": "Lightweight breathable cap designed for running and outdoor activities.",
        "price": 18.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 116,
    },
    {
        "external_id": 72,
        "title": "Leather Belt",
        "description": "Classic leather belt with a simple buckle for everyday outfits.",
        "price": 27.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 125,
    },
    {
        "external_id": 73,
        "title": "Classic Backpack",
        "description": "Roomy everyday backpack with padded storage for books and a laptop.",
        "price": 49.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 164,
    },
    {
        "external_id": 74,
        "title": "Card Holder",
        "description": "Slim card holder designed for carrying essential cards in a compact format.",
        "price": 16.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 71,
    },
    {
        "external_id": 75,
        "title": "Canvas Tote Bag",
        "description": "Reusable canvas tote bag with sturdy handles for daily shopping and errands.",
        "price": 19.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 92,
    },
    {
        "external_id": 76,
        "title": "Travel Neck Pillow",
        "description": "Soft supportive neck pillow for comfortable travel and long journeys.",
        "price": 22.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1530441687753-cc7c6b9c7a8f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 65,
    },
    {
        "external_id": 77,
        "title": "Beanie Cap",
        "description": "Soft knit beanie for keeping warm during cooler weather.",
        "price": 15.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 78,
    },
    {
        "external_id": 78,
        "title": "Classic Analog Watch",
        "description": "Elegant analog watch with a clean dial and versatile everyday styling.",
        "price": 74.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 143,
    },
    {
        "external_id": 79,
        "title": "Travel Sunglasses Case",
        "description": "Protective hard case for storing sunglasses safely while traveling.",
        "price": 13.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 59,
    },
    {
        "external_id": 80,
        "title": "Compact Umbrella",
        "description": "Lightweight foldable umbrella that fits easily inside a backpack.",
        "price": 21.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 87,
    },
    {
        "external_id": 81,
        "title": "Non Stick Frying Pan",
        "description": "Durable non stick frying pan for convenient everyday cooking.",
        "price": 32.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 176,
    },
    {
        "external_id": 82,
        "title": "Electric Kettle",
        "description": "Fast boiling electric kettle with a simple compact design.",
        "price": 39.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1594213114663-d94db9b171b9?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 203,
    },
    {
        "external_id": 83,
        "title": "French Press",
        "description": "Glass French press for making rich freshly brewed coffee at home.",
        "price": 26.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 189,
    },
    {
        "external_id": 84,
        "title": "Bamboo Cutting Board",
        "description": "Sturdy bamboo cutting board for everyday kitchen preparation.",
        "price": 24.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 98,
    },
    {
        "external_id": 85,
        "title": "Kitchen Knife Set",
        "description": "Practical kitchen knife set for slicing chopping and everyday food preparation.",
        "price": 49.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 154,
    },
    {
        "external_id": 86,
        "title": "Cotton Cushion Set",
        "description": "Soft decorative cushion covers that add comfort and style to living spaces.",
        "price": 29.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 76,
    },
    {
        "external_id": 87,
        "title": "Scented Candle",
        "description": "Pleasantly scented candle designed to create a warm relaxing atmosphere.",
        "price": 17.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 217,
    },
    {
        "external_id": 88,
        "title": "Laundry Basket",
        "description": "Lightweight laundry basket with handles for convenient home organization.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1610557892470-a5d4c8c9e3e7?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 68,
    },
    {
        "external_id": 89,
        "title": "Bathroom Organizer",
        "description": "Compact organizer for keeping toiletries and bathroom essentials neatly arranged.",
        "price": 20.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 82,
    },
    {
        "external_id": 90,
        "title": "Memory Foam Pillow",
        "description": "Supportive memory foam pillow designed for comfortable everyday sleep.",
        "price": 35.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 146,
    },
    {
        "external_id": 91,
        "title": "Makeup Brush Set",
        "description": "Complete makeup brush set with soft bristles for everyday beauty routines.",
        "price": 24.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 173,
    },
    {
        "external_id": 92,
        "title": "Gentle Face Cleanser",
        "description": "Gentle daily cleanser designed to remove impurities without feeling harsh.",
        "price": 15.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 139,
    },
    {
        "external_id": 93,
        "title": "Body Lotion",
        "description": "Lightweight body lotion that helps keep skin feeling smooth and moisturized.",
        "price": 14.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 102,
    },
    {
        "external_id": 94,
        "title": "Hair Care Shampoo",
        "description": "Everyday shampoo designed for a fresh clean hair care routine.",
        "price": 17.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 95,
    },
    {
        "external_id": 95,
        "title": "Hair Conditioner",
        "description": "Moisturizing conditioner designed to leave hair feeling soft and manageable.",
        "price": 18.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 88,
    },
    {
        "external_id": 96,
        "title": "Hand Cream",
        "description": "Nourishing hand cream for keeping hands soft and comfortable throughout the day.",
        "price": 9.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 79,
    },
    {
        "external_id": 97,
        "title": "Study Highlighter Set",
        "description": "Bright smooth highlighters for study notes planning and organization.",
        "price": 9.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 116,
    },
    {
        "external_id": 98,
        "title": "A4 Sketchbook",
        "description": "High quality sketchbook suitable for drawing illustration and creative practice.",
        "price": 18.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 94,
    },
    {
        "external_id": 99,
        "title": "Sticky Notes Pack",
        "description": "Colorful sticky notes for reminders study organization and quick messages.",
        "price": 7.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1586282391129-76a6df230234?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 73,
    },
    {
        "external_id": 100,
        "title": "Study Desk Pad",
        "description": "Large desk pad that provides a comfortable writing and study surface.",
        "price": 21.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 91,
    },
]

products.extend([
    {
        "external_id": 101,
        "title": "Gaming Mouse",
        "description": "High precision gaming mouse with adjustable sensitivity and comfortable grip.",
        "price": 39.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 198,
    },
    {
        "external_id": 102,
        "title": "Wireless Gaming Headset",
        "description": "Wireless gaming headset with immersive audio and a comfortable design.",
        "price": 89.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 176,
    },
    {
        "external_id": 103,
        "title": "Laptop Backpack",
        "description": "Protective laptop backpack with padded compartments and practical storage.",
        "price": 59.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 154,
    },
    {
        "external_id": 104,
        "title": "Wireless Charger",
        "description": "Compact wireless charging pad for compatible smartphones and devices.",
        "price": 24.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1609592424848-0a9c4f8e6c20?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 112,
    },
    {
        "external_id": 105,
        "title": "Smart Home Speaker",
        "description": "Compact smart speaker for music playback and everyday home assistance.",
        "price": 69.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 143,
    },
    {
        "external_id": 106,
        "title": "Fitness Smart Band",
        "description": "Lightweight fitness band with activity tracking and daily notifications.",
        "price": 49.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 127,
    },
    {
        "external_id": 107,
        "title": "Mini Projector",
        "description": "Portable mini projector for movies presentations and home entertainment.",
        "price": 159.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 136,
    },
    {
        "external_id": 108,
        "title": "USB Microphone",
        "description": "USB microphone designed for streaming meetings podcasts and voice recording.",
        "price": 74.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1589903308904-1010c2294adc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 189,
    },
    {
        "external_id": 109,
        "title": "External Monitor",
        "description": "Full HD external monitor with a bright display for work study and entertainment.",
        "price": 179.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 221,
    },
    {
        "external_id": 110,
        "title": "Bluetooth Adapter",
        "description": "Compact Bluetooth adapter for adding wireless connectivity to compatible devices.",
        "price": 16.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 88,
    },

    {
        "external_id": 111,
        "title": "Cotton Trousers",
        "description": "Comfortable cotton trousers suitable for casual everyday outfits.",
        "price": 44.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 104,
    },
    {
        "external_id": 112,
        "title": "Winter Coat",
        "description": "Warm winter coat designed for comfortable cold weather layering.",
        "price": 119.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 167,
    },
    {
        "external_id": 113,
        "title": "Graphic T Shirt",
        "description": "Casual graphic t shirt made from soft comfortable cotton fabric.",
        "price": 24.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 118,
    },
    {
        "external_id": 114,
        "title": "Casual Shorts",
        "description": "Relaxed casual shorts with comfortable fabric for everyday wear.",
        "price": 27.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1562886877-3c3e8f4c6f65?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 91,
    },
    {
        "external_id": 115,
        "title": "Women's Cardigan",
        "description": "Soft lightweight cardigan suitable for layering and everyday outfits.",
        "price": 49.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 126,
    },
    {
        "external_id": 116,
        "title": "Denim Shorts",
        "description": "Classic denim shorts with a comfortable fit for casual summer outfits.",
        "price": 34.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 103,
    },
    {
        "external_id": 117,
        "title": "Puffer Vest",
        "description": "Lightweight insulated vest for comfortable outdoor layering.",
        "price": 69.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 117,
    },
    {
        "external_id": 118,
        "title": "Polo T Shirt",
        "description": "Classic polo shirt with a comfortable fit for casual and smart outfits.",
        "price": 32.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1625910513413-5fc45c2f6c1d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 115,
    },
    {
        "external_id": 119,
        "title": "Long Sleeve Shirt",
        "description": "Versatile long sleeve shirt suitable for casual everyday styling.",
        "price": 36.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 109,
    },
    {
        "external_id": 120,
        "title": "Lightweight Rain Jacket",
        "description": "Water resistant lightweight jacket for unpredictable weather.",
        "price": 64.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 97,
    },

    {
        "external_id": 121,
        "title": "Walking Shoes",
        "description": "Comfortable walking shoes designed for everyday movement and long walks.",
        "price": 69.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 152,
    },
    {
        "external_id": 122,
        "title": "Running Sneakers",
        "description": "Responsive running sneakers with lightweight cushioning for daily training.",
        "price": 94.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 241,
    },
    {
        "external_id": 123,
        "title": "Leather Boots",
        "description": "Classic leather boots designed for durable everyday wear.",
        "price": 109.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 124,
        "title": "Casual Loafers",
        "description": "Comfortable loafers with a clean design for smart casual outfits.",
        "price": 74.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 106,
    },
    {
        "external_id": 125,
        "title": "High Top Sneakers",
        "description": "Classic high top sneakers with a comfortable everyday design.",
        "price": 69.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 143,
    },
    {
        "external_id": 126,
        "title": "Training Shoes",
        "description": "Stable training shoes designed for gym workouts and active routines.",
        "price": 84.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 158,
    },
    {
        "external_id": 127,
        "title": "Walking Sandals",
        "description": "Lightweight walking sandals with comfortable support for warm weather.",
        "price": 39.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 87,
    },
    {
        "external_id": 128,
        "title": "Slip On Sneakers",
        "description": "Easy slip on sneakers with cushioned support for everyday activities.",
        "price": 59.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1520256862855-398228c41684?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 121,
    },
    {
        "external_id": 129,
        "title": "Basketball Shoes",
        "description": "Supportive basketball shoes with cushioning and traction for the court.",
        "price": 99.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 186,
    },
    {
        "external_id": 130,
        "title": "Outdoor Hiking Boots",
        "description": "Durable hiking boots designed for trails and outdoor adventures.",
        "price": 124.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.7,
        "rating_count": 174,
    },

    {
        "external_id": 131,
        "title": "Travel Backpack",
        "description": "Spacious travel backpack with multiple compartments for organized packing.",
        "price": 64.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 167,
    },
    {
        "external_id": 132,
        "title": "Laptop Sleeve",
        "description": "Protective padded laptop sleeve with a slim travel friendly design.",
        "price": 27.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 119,
    },
    {
        "external_id": 133,
        "title": "Leather Handbag",
        "description": "Elegant leather handbag with practical storage for everyday essentials.",
        "price": 89.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 146,
    },
    {
        "external_id": 134,
        "title": "Travel Wallet",
        "description": "Compact travel wallet with space for cards documents and cash.",
        "price": 32.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 108,
    },
    {
        "external_id": 135,
        "title": "Polarized Sunglasses",
        "description": "Stylish polarized sunglasses with lightweight frames for outdoor use.",
        "price": 39.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 139,
    },
    {
        "external_id": 136,
        "title": "Digital Sports Watch",
        "description": "Sporty digital watch with a durable design for active lifestyles.",
        "price": 54.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 116,
    },
    {
        "external_id": 137,
        "title": "Minimalist Crossbody Bag",
        "description": "Compact crossbody bag with a clean minimalist design for everyday use.",
        "price": 37.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 94,
    },
    {
        "external_id": 138,
        "title": "Foldable Travel Bag",
        "description": "Lightweight foldable bag that is convenient for travel and shopping.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 82,
    },
    {
        "external_id": 139,
        "title": "Key Organizer",
        "description": "Compact key organizer that keeps everyday keys neatly arranged.",
        "price": 14.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 65,
    },
    {
        "external_id": 140,
        "title": "Travel Toiletry Bag",
        "description": "Organized toiletry bag with multiple compartments for travel essentials.",
        "price": 25.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553484771-047a44eee27b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 91,
    },

    {
        "external_id": 141,
        "title": "Air Fryer",
        "description": "Compact air fryer for convenient everyday cooking with less oil.",
        "price": 89.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 234,
    },
    {
        "external_id": 142,
        "title": "Toaster",
        "description": "Compact toaster with multiple browning settings for quick breakfasts.",
        "price": 34.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 118,
    },
    {
        "external_id": 143,
        "title": "Blender",
        "description": "Powerful countertop blender for smoothies sauces and everyday recipes.",
        "price": 59.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 187,
    },
    {
        "external_id": 144,
        "title": "Dinner Plate Set",
        "description": "Modern ceramic dinner plate set for everyday meals and entertaining.",
        "price": 39.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 102,
    },
    {
        "external_id": 145,
        "title": "Glass Storage Containers",
        "description": "Reusable glass food containers for organized kitchen storage.",
        "price": 34.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1583032015879-e5022cb8eeba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 128,
    },
    {
        "external_id": 146,
        "title": "Kitchen Scale",
        "description": "Digital kitchen scale for accurate ingredient measurements and recipes.",
        "price": 19.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 83,
    },
    {
        "external_id": 147,
        "title": "Bedside Lamp",
        "description": "Compact bedside lamp with a warm light for bedrooms and reading areas.",
        "price": 29.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 97,
    },
    {
        "external_id": 148,
        "title": "Decorative Wall Clock",
        "description": "Modern wall clock with a clean design for home and office spaces.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 74,
    },
    {
        "external_id": 149,
        "title": "Storage Basket Set",
        "description": "Practical storage baskets for organizing bedrooms living rooms and shelves.",
        "price": 31.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 89,
    },
    {
        "external_id": 150,
        "title": "Kitchen Utensil Set",
        "description": "Complete kitchen utensil set for everyday cooking and food preparation.",
        "price": 29.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 136,
    },

    {
        "external_id": 151,
        "title": "Night Face Cream",
        "description": "Rich moisturizing face cream designed for a simple evening skincare routine.",
        "price": 29.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 142,
    },
    {
        "external_id": 152,
        "title": "Vitamin C Serum",
        "description": "Lightweight facial serum designed for a refreshing skincare routine.",
        "price": 31.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 157,
    },
    {
        "external_id": 153,
        "title": "Face Wash",
        "description": "Gentle everyday face wash for a clean and refreshed feeling.",
        "price": 13.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 118,
    },
    {
        "external_id": 154,
        "title": "Body Wash",
        "description": "Refreshing body wash for a clean and comfortable daily routine.",
        "price": 12.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 93,
    },
    {
        "external_id": 155,
        "title": "Hair Styling Cream",
        "description": "Lightweight styling cream for flexible everyday hair styling.",
        "price": 16.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 87,
    },
    {
        "external_id": 156,
        "title": "Face Mask Set",
        "description": "Skincare mask set for a relaxing addition to weekly beauty routines.",
        "price": 21.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 104,
    },
    {
        "external_id": 157,
        "title": "Makeup Organizer",
        "description": "Clear makeup organizer for neatly storing cosmetics and beauty essentials.",
        "price": 28.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 121,
    },
    {
        "external_id": 158,
        "title": "Perfume Gift Set",
        "description": "Elegant fragrance gift set suitable for everyday use and special occasions.",
        "price": 59.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 164,
    },
    {
        "external_id": 159,
        "title": "Lip Gloss",
        "description": "Lightweight lip gloss with a smooth finish for everyday beauty looks.",
        "price": 11.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1607602132700-068b8c6d1a73?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 76,
    },
    {
        "external_id": 160,
        "title": "Hand Care Set",
        "description": "Simple hand care set with moisturizing products for daily use.",
        "price": 22.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 98,
    },

    {
        "external_id": 161,
        "title": "Ballpoint Pen Set",
        "description": "Smooth writing ballpoint pens suitable for school office and everyday notes.",
        "price": 8.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 84,
    },
    {
        "external_id": 162,
        "title": "Hardcover Journal",
        "description": "Premium hardcover journal for notes planning and personal writing.",
        "price": 19.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 117,
    },
    {
        "external_id": 163,
        "title": "Weekly Planner",
        "description": "Simple weekly planner for organizing tasks appointments and goals.",
        "price": 14.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 129,
    },
    {
        "external_id": 164,
        "title": "Colored Pencil Set",
        "description": "Set of colorful pencils for sketching coloring and creative projects.",
        "price": 17.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 101,
    },
    {
        "external_id": 165,
        "title": "Watercolor Paint Set",
        "description": "Beginner friendly watercolor set for creative artwork and illustration.",
        "price": 22.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 92,
    },
    {
        "external_id": 166,
        "title": "Document Folder Set",
        "description": "Durable document folders for organizing papers projects and notes.",
        "price": 12.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 68,
    },
    {
        "external_id": 167,
        "title": "Desk Calendar",
        "description": "Compact desk calendar for tracking important dates tasks and reminders.",
        "price": 11.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 83,
    },
    {
        "external_id": 168,
        "title": "Eraser Pack",
        "description": "Soft clean erasers suitable for school office and drawing work.",
        "price": 6.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 61,
    },
    {
        "external_id": 169,
        "title": "Drawing Marker Set",
        "description": "Colorful drawing markers for creative projects illustrations and notes.",
        "price": 16.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 95,
    },
    {
        "external_id": 170,
        "title": "Clipboard Set",
        "description": "Durable clipboard set for organizing papers forms and everyday documents.",
        "price": 13.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 72,
    },

    {
        "external_id": 171,
        "title": "Exercise Mat",
        "description": "Comfortable exercise mat for stretching workouts and floor exercises.",
        "price": 27.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 148,
    },
    {
        "external_id": 172,
        "title": "Kettlebell",
        "description": "Compact kettlebell for strength training and full body workouts.",
        "price": 49.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 129,
    },
    {
        "external_id": 173,
        "title": "Pull Up Bar",
        "description": "Doorway pull up bar for convenient upper body workouts at home.",
        "price": 39.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 117,
    },
    {
        "external_id": 174,
        "title": "Workout Gloves",
        "description": "Comfortable workout gloves with grip support for strength training.",
        "price": 18.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 86,
    },
    {
        "external_id": 175,
        "title": "Gym Water Bottle",
        "description": "Durable reusable water bottle designed for workouts and active routines.",
        "price": 19.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 135,
    },
    {
        "external_id": 176,
        "title": "Exercise Ball",
        "description": "Durable exercise ball for balance stretching and home fitness routines.",
        "price": 29.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 91,
    },
    {
        "external_id": 177,
        "title": "Ankle Weights",
        "description": "Adjustable ankle weights for adding resistance to walking and workouts.",
        "price": 24.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 73,
    },
    {
        "external_id": 178,
        "title": "Workout Bench",
        "description": "Adjustable workout bench for strength exercises and home training.",
        "price": 119.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 124,
    },
    {
        "external_id": 179,
        "title": "Yoga Block Set",
        "description": "Lightweight yoga blocks for improved support balance and stretching.",
        "price": 16.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 89,
    },
    {
        "external_id": 180,
        "title": "Sports Towel",
        "description": "Quick drying sports towel designed for workouts gym sessions and travel.",
        "price": 12.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 77,
    },

    {
        "external_id": 181,
        "title": "Wireless Earphones",
        "description": "Compact wireless earphones with clear audio and a portable charging case.",
        "price": 54.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 218,
    },
    {
        "external_id": 182,
        "title": "Smart Home Camera",
        "description": "Compact smart camera designed for convenient indoor home monitoring.",
        "price": 79.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 131,
    },
    {
        "external_id": 183,
        "title": "E Reader",
        "description": "Lightweight digital reader designed for comfortable reading at home or while traveling.",
        "price": 129.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 184,
    },
    {
        "external_id": 184,
        "title": "Portable Bluetooth Radio",
        "description": "Compact Bluetooth radio with wireless music playback and portable design.",
        "price": 44.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 79,
    },
    {
        "external_id": 185,
        "title": "Smart Desk Clock",
        "description": "Modern digital desk clock with a clean display for home and office spaces.",
        "price": 32.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 91,
    },
    {
        "external_id": 186,
        "title": "Cable Organizer",
        "description": "Simple cable organizer for keeping chargers wires and desk accessories tidy.",
        "price": 12.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553484771-047a44eee27b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 83,
    },
    {
        "external_id": 187,
        "title": "Travel Luggage",
        "description": "Durable travel luggage with organized compartments and smooth wheels.",
        "price": 139.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 171,
    },
    {
        "external_id": 188,
        "title": "Passport Holder",
        "description": "Slim passport holder with storage for travel cards and documents.",
        "price": 19.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 74,
    },
    {
        "external_id": 189,
        "title": "Travel Packing Cubes",
        "description": "Set of lightweight packing cubes for keeping luggage organized.",
        "price": 26.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 108,
    },
    {
        "external_id": 190,
        "title": "Everyday Tote",
        "description": "Spacious everyday tote bag suitable for shopping work and casual use.",
        "price": 24.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 92,
    },

    {
        "external_id": 191,
        "title": "Reading Glasses",
        "description": "Lightweight reading glasses with a simple comfortable frame.",
        "price": 17.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 67,
    },
    {
        "external_id": 192,
        "title": "Desk Mat",
        "description": "Large desk mat providing a smooth comfortable surface for work and gaming.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 123,
    },
    {
        "external_id": 193,
        "title": "Ceramic Vase",
        "description": "Minimal ceramic vase for adding a simple decorative touch to living spaces.",
        "price": 23.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1578500351865-d6c3706f4f4d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 82,
    },
    {
        "external_id": 194,
        "title": "Throw Blanket",
        "description": "Soft decorative throw blanket for comfortable evenings at home.",
        "price": 39.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 115,
    },
    {
        "external_id": 195,
        "title": "Kitchen Apron",
        "description": "Comfortable kitchen apron with practical pockets for everyday cooking.",
        "price": 21.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 71,
    },
    {
        "external_id": 196,
        "title": "Makeup Mirror",
        "description": "Compact makeup mirror with a clean design for daily beauty routines.",
        "price": 34.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 96,
    },
    {
        "external_id": 197,
        "title": "Nail Care Kit",
        "description": "Compact nail care kit containing essential tools for everyday grooming.",
        "price": 18.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 84,
    },
    {
        "external_id": 198,
        "title": "Creative Drawing Pad",
        "description": "Quality drawing pad suitable for sketching illustration and creative practice.",
        "price": 15.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 89,
    },
    {
        "external_id": 199,
        "title": "Premium Notebook",
        "description": "Premium notebook with quality paper for writing planning and journaling.",
        "price": 17.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 112,
    },
    {
        "external_id": 200,
        "title": "Home Workout Kit",
        "description": "Convenient home workout kit with basic equipment for everyday exercise.",
        "price": 79.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 137,
    },
])

for item in products:
    category, _ = Category.objects.get_or_create(
        name=item["category"]
    )

    Product.objects.update_or_create(
        external_id=item["external_id"],
        defaults={
            "title": item["title"],
            "description": item["description"],
            "price": item["price"],
            "category": category,
            "image": item["image"],
            "rating": item["rating"],
            "rating_count": item["rating_count"],
        },
    )


print(f"Successfully added {len(products)} products.")
