import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shopgen.settings")
django.setup()

from products.models import Category, Product


products = [
    {
        "external_id": 1,
        "title": "Wireless Headphones",
        "description": "Comfortable wireless headphones with clear sound and long battery life.",
        "price": 59.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 120,
    },
    {
        "external_id": 2,
        "title": "Gaming Keyboard",
        "description": "Mechanical gaming keyboard with RGB lighting and responsive keys.",
        "price": 79.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 210,
    },
    {
        "external_id": 3,
        "title": "Casual T Shirt",
        "description": "Comfortable casual cotton t shirt suitable for everyday wear.",
        "price": 19.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 95,
    },
    {
        "external_id": 4,
        "title": "Smart Watch",
        "description": "Smart watch with fitness tracking notifications and health monitoring features.",
        "price": 129.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 180,
    },
    {
        "external_id": 5,
        "title": "Backpack",
        "description": "Durable everyday backpack with multiple compartments.",
        "price": 39.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 150,
    },
    {
        "external_id": 6,
        "title": "Running Shoes",
        "description": "Lightweight running shoes designed for comfort and daily exercise.",
        "price": 89.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 230,
    },
    {
        "external_id": 7,
        "title": "Denim Jacket",
        "description": "Classic denim jacket suitable for casual outfits.",
        "price": 69.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 80,
    },
    {
        "external_id": 8,
        "title": "Bluetooth Speaker",
        "description": "Portable Bluetooth speaker with powerful sound and compact design.",
        "price": 49.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 175,
    },
    {
        "external_id": 9,
        "title": "Leather Wallet",
        "description": "Compact leather wallet with multiple card and cash compartments.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 110,
    },
    {
        "external_id": 10,
        "title": "Sports Shoes",
        "description": "Comfortable sports shoes designed for workouts and outdoor activities.",
        "price": 74.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 140,
    },
    {
        "external_id": 11,
        "title": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with precise tracking and quiet clicks.",
        "price": 24.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 165,
    },
    {
        "external_id": 12,
        "title": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand for a cleaner and more comfortable desk setup.",
        "price": 34.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 13,
        "title": "USB C Hub",
        "description": "Compact USB C hub with multiple ports for laptops and tablets.",
        "price": 32.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 118,
    },
    {
        "external_id": 14,
        "title": "Portable Power Bank",
        "description": "High capacity portable power bank with fast charging support.",
        "price": 44.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1609592424848-0a9c4f8e6c20?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 205,
    },
    {
        "external_id": 15,
        "title": "Instant Camera",
        "description": "Fun instant camera for quick photos with a retro inspired look.",
        "price": 99.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 188,
    },
    {
        "external_id": 16,
        "title": "Cotton Hoodie",
        "description": "Soft cotton hoodie with a relaxed fit for everyday comfort.",
        "price": 44.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 145,
    },
    {
        "external_id": 17,
        "title": "Slim Fit Jeans",
        "description": "Versatile slim fit jeans with stretch fabric for everyday wear.",
        "price": 54.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 170,
    },
    {
        "external_id": 18,
        "title": "Casual Polo Shirt",
        "description": "Classic polo shirt made from breathable fabric for smart casual outfits.",
        "price": 34.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1625910513413-5fc45c2f6c1d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 102,
    },
    {
        "external_id": 19,
        "title": "Summer Dress",
        "description": "Lightweight summer dress with a comfortable relaxed silhouette.",
        "price": 49.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 156,
    },
    {
        "external_id": 20,
        "title": "Oversized Sweatshirt",
        "description": "Cozy oversized sweatshirt for relaxed everyday styling.",
        "price": 39.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 126,
    },
    {
        "external_id": 21,
        "title": "Canvas Sneakers",
        "description": "Minimal canvas sneakers designed for everyday casual outfits.",
        "price": 49.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 214,
    },
    {
        "external_id": 22,
        "title": "Trail Hiking Shoes",
        "description": "Supportive hiking shoes with durable traction for outdoor adventures.",
        "price": 109.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 190,
    },
    {
        "external_id": 23,
        "title": "Classic Sneakers",
        "description": "Clean everyday sneakers with a timeless low profile design.",
        "price": 64.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 225,
    },
    {
        "external_id": 24,
        "title": "Slip On Shoes",
        "description": "Easy slip on shoes with cushioned support for daily use.",
        "price": 54.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1520256862855-398228c41684?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 92,
    },
    {
        "external_id": 25,
        "title": "Lightweight Trainers",
        "description": "Breathable trainers built for gym sessions and active routines.",
        "price": 84.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 160,
    },
    {
        "external_id": 26,
        "title": "Crossbody Bag",
        "description": "Compact crossbody bag with practical storage for daily essentials.",
        "price": 42.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 124,
    },
    {
        "external_id": 27,
        "title": "Travel Duffel Bag",
        "description": "Spacious duffel bag designed for weekend trips and short travel.",
        "price": 69.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 142,
    },
    {
        "external_id": 28,
        "title": "Aviator Sunglasses",
        "description": "Classic aviator sunglasses with a lightweight metal frame.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 98,
    },
    {
        "external_id": 29,
        "title": "Minimalist Watch",
        "description": "Clean minimalist watch with a simple dial and comfortable strap.",
        "price": 89.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 176,
    },
    {
        "external_id": 30,
        "title": "Travel Organizer",
        "description": "Compact travel organizer for cables documents and small essentials.",
        "price": 24.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553484771-047a44eee27b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 88,
    },
    {
        "external_id": 31,
        "title": "Ceramic Coffee Mug",
        "description": "Modern ceramic coffee mug with a comfortable handle and matte finish.",
        "price": 14.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 240,
    },
    {
        "external_id": 32,
        "title": "Stainless Water Bottle",
        "description": "Insulated stainless steel bottle that keeps drinks cool for hours.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 198,
    },
    {
        "external_id": 33,
        "title": "Desk Lamp",
        "description": "Modern desk lamp with adjustable lighting for work or study spaces.",
        "price": 36.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 133,
    },
    {
        "external_id": 34,
        "title": "Plant Pot Set",
        "description": "Set of simple indoor plant pots for desks shelves and windowsills.",
        "price": 22.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 104,
    },
    {
        "external_id": 35,
        "title": "Kitchen Storage Set",
        "description": "Reusable kitchen storage containers for keeping pantry ingredients organized.",
        "price": 31.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1583032015879-e5022cb8eeba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 76,
    },
    {
        "external_id": 36,
        "title": "Moisturizing Face Cream",
        "description": "Light daily face moisturizer designed to leave skin feeling soft and hydrated.",
        "price": 18.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 185,
    },
    {
        "external_id": 37,
        "title": "Hydrating Face Serum",
        "description": "Lightweight hydrating serum for a simple everyday skincare routine.",
        "price": 26.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 151,
    },
    {
        "external_id": 38,
        "title": "Aloe Vera Gel",
        "description": "Soothing aloe vera gel for a refreshing addition to daily skincare.",
        "price": 12.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 119,
    },
    {
        "external_id": 39,
        "title": "Lip Care Balm",
        "description": "Simple moisturizing lip balm for comfortable everyday lip care.",
        "price": 8.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1607602132700-068b8c6d1a73?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 83,
    },
    {
        "external_id": 40,
        "title": "Everyday Perfume",
        "description": "Fresh everyday fragrance with a clean and versatile scent profile.",
        "price": 39.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 172,
    },
    {
        "external_id": 41,
        "title": "Mechanical Pencil Set",
        "description": "Smooth mechanical pencils with refill leads for study and office work.",
        "price": 10.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 72,
    },
    {
        "external_id": 42,
        "title": "Daily Planner",
        "description": "Undated daily planner for organizing tasks goals and notes.",
        "price": 16.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 141,
    },
    {
        "external_id": 43,
        "title": "Notebook Set",
        "description": "Set of lined notebooks for class notes journaling and planning.",
        "price": 13.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 126,
    },
    {
        "external_id": 44,
        "title": "Desk Organizer",
        "description": "Compact desk organizer for pens cables notes and small accessories.",
        "price": 18.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 97,
    },
    {
        "external_id": 45,
        "title": "Premium Gel Pens",
        "description": "Smooth writing gel pens with quick drying ink for everyday writing.",
        "price": 11.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 108,
    },
    {
        "external_id": 46,
        "title": "Yoga Mat",
        "description": "Cushioned non slip yoga mat suitable for stretching yoga and home workouts.",
        "price": 29.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 215,
    },
    {
        "external_id": 47,
        "title": "Resistance Bands",
        "description": "Portable resistance bands for strength training and mobility exercises.",
        "price": 21.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 149,
    },
    {
        "external_id": 48,
        "title": "Adjustable Dumbbell",
        "description": "Space saving adjustable dumbbell for convenient strength workouts at home.",
        "price": 64.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 49,
        "title": "Fitness Jump Rope",
        "description": "Lightweight speed jump rope for cardio workouts and conditioning.",
        "price": 15.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1517963879433-6ad2b056d6f4?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 95,
    },
    {
        "external_id": 50,
        "title": "Foam Roller",
        "description": "Textured foam roller for warmups recovery and post workout mobility.",
        "price": 25.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 113,
    },
]


for item in products:
    category, _ = Category.objects.get_or_create(
        name=item["category"]
    )

    Product.objects.update_or_create(
        external_id=item["external_id"],
        defaults={
            "title": item["title"],
            "description": item["description"],
            "price": item["price"],
            "category": category,
            "image": item["image"],
            "rating": item["rating"],
            "rating_count": item["rating_count"],
        },
    )


print(f"Successfully added {len(products)} products.")
