import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shopgen.settings")
django.setup()

from products.models import Category, Product


products = [
    {
        "external_id": 1,
        "title": "Wireless Headphones",
        "description": "Comfortable wireless headphones with clear sound and long battery life.",
        "price": 59.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 120,
    },
    {
        "external_id": 2,
        "title": "Gaming Keyboard",
        "description": "Mechanical gaming keyboard with RGB lighting and responsive keys.",
        "price": 79.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 210,
    },
    {
        "external_id": 3,
        "title": "Casual T Shirt",
        "description": "Comfortable casual cotton t shirt suitable for everyday wear.",
        "price": 19.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 95,
    },
    {
        "external_id": 4,
        "title": "Smart Watch",
        "description": "Smart watch with fitness tracking notifications and health monitoring features.",
        "price": 129.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 180,
    },
    {
        "external_id": 5,
        "title": "Backpack",
        "description": "Durable everyday backpack with multiple compartments.",
        "price": 39.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 150,
    },
    {
        "external_id": 6,
        "title": "Running Shoes",
        "description": "Lightweight running shoes designed for comfort and daily exercise.",
        "price": 89.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 230,
    },
    {
        "external_id": 7,
        "title": "Denim Jacket",
        "description": "Classic denim jacket suitable for casual outfits.",
        "price": 69.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 80,
    },
    {
        "external_id": 8,
        "title": "Bluetooth Speaker",
        "description": "Portable Bluetooth speaker with powerful sound and compact design.",
        "price": 49.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 175,
    },
    {
        "external_id": 9,
        "title": "Leather Wallet",
        "description": "Compact leather wallet with multiple card and cash compartments.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 110,
    },
    {
        "external_id": 10,
        "title": "Sports Shoes",
        "description": "Comfortable sports shoes designed for workouts and outdoor activities.",
        "price": 74.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 140,
    },
    {
        "external_id": 11,
        "title": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with precise tracking and quiet clicks.",
        "price": 24.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 165,
    },
    {
        "external_id": 12,
        "title": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand for a cleaner and more comfortable desk setup.",
        "price": 34.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 13,
        "title": "USB C Hub",
        "description": "Compact USB C hub with multiple ports for laptops and tablets.",
        "price": 32.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 118,
    },
    {
        "external_id": 14,
        "title": "Portable Power Bank",
        "description": "High capacity portable power bank with fast charging support.",
        "price": 44.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1609592424848-0a9c4f8e6c20?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 205,
    },
    {
        "external_id": 15,
        "title": "Instant Camera",
        "description": "Fun instant camera for quick photos with a retro inspired look.",
        "price": 99.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 188,
    },
    {
        "external_id": 16,
        "title": "Cotton Hoodie",
        "description": "Soft cotton hoodie with a relaxed fit for everyday comfort.",
        "price": 44.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 145,
    },
    {
        "external_id": 17,
        "title": "Slim Fit Jeans",
        "description": "Versatile slim fit jeans with stretch fabric for everyday wear.",
        "price": 54.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 170,
    },
    {
        "external_id": 18,
        "title": "Casual Polo Shirt",
        "description": "Classic polo shirt made from breathable fabric for smart casual outfits.",
        "price": 34.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1625910513413-5fc45c2f6c1d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 102,
    },
    {
        "external_id": 19,
        "title": "Summer Dress",
        "description": "Lightweight summer dress with a comfortable relaxed silhouette.",
        "price": 49.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 156,
    },
    {
        "external_id": 20,
        "title": "Oversized Sweatshirt",
        "description": "Cozy oversized sweatshirt for relaxed everyday styling.",
        "price": 39.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 126,
    },
    {
        "external_id": 21,
        "title": "Canvas Sneakers",
        "description": "Minimal canvas sneakers designed for everyday casual outfits.",
        "price": 49.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 214,
    },
    {
        "external_id": 22,
        "title": "Trail Hiking Shoes",
        "description": "Supportive hiking shoes with durable traction for outdoor adventures.",
        "price": 109.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 190,
    },
    {
        "external_id": 23,
        "title": "Classic Sneakers",
        "description": "Clean everyday sneakers with a timeless low profile design.",
        "price": 64.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 225,
    },
    {
        "external_id": 24,
        "title": "Slip On Shoes",
        "description": "Easy slip on shoes with cushioned support for daily use.",
        "price": 54.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1520256862855-398228c41684?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 92,
    },
    {
        "external_id": 25,
        "title": "Lightweight Trainers",
        "description": "Breathable trainers built for gym sessions and active routines.",
        "price": 84.99,
        "category": "Footwear",
        "image": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 160,
    },
    {
        "external_id": 26,
        "title": "Crossbody Bag",
        "description": "Compact crossbody bag with practical storage for daily essentials.",
        "price": 42.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 124,
    },
    {
        "external_id": 27,
        "title": "Travel Duffel Bag",
        "description": "Spacious duffel bag designed for weekend trips and short travel.",
        "price": 69.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 142,
    },
    {
        "external_id": 28,
        "title": "Aviator Sunglasses",
        "description": "Classic aviator sunglasses with a lightweight metal frame.",
        "price": 29.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 98,
    },
    {
        "external_id": 29,
        "title": "Minimalist Watch",
        "description": "Clean minimalist watch with a simple dial and comfortable strap.",
        "price": 89.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 176,
    },
    {
        "external_id": 30,
        "title": "Travel Organizer",
        "description": "Compact travel organizer for cables documents and small essentials.",
        "price": 24.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1553484771-047a44eee27b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 88,
    },
    {
        "external_id": 31,
        "title": "Ceramic Coffee Mug",
        "description": "Modern ceramic coffee mug with a comfortable handle and matte finish.",
        "price": 14.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 240,
    },
    {
        "external_id": 32,
        "title": "Stainless Water Bottle",
        "description": "Insulated stainless steel bottle that keeps drinks cool for hours.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 198,
    },
    {
        "external_id": 33,
        "title": "Desk Lamp",
        "description": "Modern desk lamp with adjustable lighting for work or study spaces.",
        "price": 36.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 133,
    },
    {
        "external_id": 34,
        "title": "Plant Pot Set",
        "description": "Set of simple indoor plant pots for desks shelves and windowsills.",
        "price": 22.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 104,
    },
    {
        "external_id": 35,
        "title": "Kitchen Storage Set",
        "description": "Reusable kitchen storage containers for keeping pantry ingredients organized.",
        "price": 31.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1583032015879-e5022cb8eeba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 76,
    },
    {
        "external_id": 36,
        "title": "Moisturizing Face Cream",
        "description": "Light daily face moisturizer designed to leave skin feeling soft and hydrated.",
        "price": 18.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 185,
    },
    {
        "external_id": 37,
        "title": "Hydrating Face Serum",
        "description": "Lightweight hydrating serum for a simple everyday skincare routine.",
        "price": 26.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 151,
    },
    {
        "external_id": 38,
        "title": "Aloe Vera Gel",
        "description": "Soothing aloe vera gel for a refreshing addition to daily skincare.",
        "price": 12.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 119,
    },
    {
        "external_id": 39,
        "title": "Lip Care Balm",
        "description": "Simple moisturizing lip balm for comfortable everyday lip care.",
        "price": 8.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1607602132700-068b8c6d1a73?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 83,
    },
    {
        "external_id": 40,
        "title": "Everyday Perfume",
        "description": "Fresh everyday fragrance with a clean and versatile scent profile.",
        "price": 39.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 172,
    },
    {
        "external_id": 41,
        "title": "Mechanical Pencil Set",
        "description": "Smooth mechanical pencils with refill leads for study and office work.",
        "price": 10.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 72,
    },
    {
        "external_id": 42,
        "title": "Daily Planner",
        "description": "Undated daily planner for organizing tasks goals and notes.",
        "price": 16.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 141,
    },
    {
        "external_id": 43,
        "title": "Notebook Set",
        "description": "Set of lined notebooks for class notes journaling and planning.",
        "price": 13.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 126,
    },
    {
        "external_id": 44,
        "title": "Desk Organizer",
        "description": "Compact desk organizer for pens cables notes and small accessories.",
        "price": 18.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 97,
    },
    {
        "external_id": 45,
        "title": "Premium Gel Pens",
        "description": "Smooth writing gel pens with quick drying ink for everyday writing.",
        "price": 11.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 108,
    },
    {
        "external_id": 46,
        "title": "Yoga Mat",
        "description": "Cushioned non slip yoga mat suitable for stretching yoga and home workouts.",
        "price": 29.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 215,
    },
    {
        "external_id": 47,
        "title": "Resistance Bands",
        "description": "Portable resistance bands for strength training and mobility exercises.",
        "price": 21.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 149,
    },
    {
        "external_id": 48,
        "title": "Adjustable Dumbbell",
        "description": "Space saving adjustable dumbbell for convenient strength workouts at home.",
        "price": 64.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 49,
        "title": "Fitness Jump Rope",
        "description": "Lightweight speed jump rope for cardio workouts and conditioning.",
        "price": 15.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1517963879433-6ad2b056d6f4?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 95,
    },
    {
        "external_id": 50,
        "title": "Foam Roller",
        "description": "Textured foam roller for warmups recovery and post workout mobility.",
        "price": 25.99,
        "category": "Fitness",
        "image": "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 113,
    },


    {
        "external_id": 51,
        "title": "4K Smart TV",
        "description": "Ultra HD smart television with vivid colors and built in streaming apps.",
        "price": 399.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 245,
    },
    {
        "external_id": 52,
        "title": "Noise Cancelling Earbuds",
        "description": "Compact wireless earbuds with active noise cancellation and charging case.",
        "price": 79.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 320,
    },
    {
        "external_id": 53,
        "title": "Tablet 10 Inch",
        "description": "Slim tablet with a bright display for entertainment study and browsing.",
        "price": 189.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 178,
    },
    {
        "external_id": 54,
        "title": "Webcam Full HD",
        "description": "Full HD webcam with clear video for classes meetings and streaming.",
        "price": 54.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 114,
    },
    {
        "external_id": 55,
        "title": "Portable SSD",
        "description": "Fast compact solid state drive for reliable file storage and backups.",
        "price": 89.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.7,
        "rating_count": 267,
    },
    {
        "external_id": 56,
        "title": "Smartphone Tripod",
        "description": "Adjustable smartphone tripod for photography video calls and content creation.",
        "price": 28.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170315870-ef7c0b6b0e7b?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 86,
    },
    {
        "external_id": 57,
        "title": "LED Desk Strip",
        "description": "Flexible LED light strip for adding ambient lighting to a desk setup.",
        "price": 19.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 137,
    },
    {
        "external_id": 58,
        "title": "Bluetooth Mechanical Keyboard",
        "description": "Wireless mechanical keyboard with tactile switches and a compact layout.",
        "price": 94.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 189,
    },
    {
        "external_id": 59,
        "title": "Action Camera",
        "description": "Compact action camera for travel sports and outdoor adventures.",
        "price": 149.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 154,
    },
    {
        "external_id": 60,
        "title": "Smart LED Bulb",
        "description": "WiFi enabled smart bulb with adjustable brightness and color settings.",
        "price": 15.99,
        "category": "Electronics",
        "image": "https://images.unsplash.com/photo-1550985543-f47c0f4c8e0d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 121,
    },
    {
        "external_id": 61,
        "title": "Formal Shirt",
        "description": "Crisp formal shirt designed for office wear presentations and events.",
        "price": 42.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 139,
    },
    {
        "external_id": 62,
        "title": "Chino Trousers",
        "description": "Versatile chino trousers with a clean fit for casual and smart outfits.",
        "price": 46.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 118,
    },
    {
        "external_id": 63,
        "title": "Flannel Shirt",
        "description": "Soft checked flannel shirt that works well for relaxed everyday outfits.",
        "price": 38.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 127,
    },
    {
        "external_id": 64,
        "title": "Zip Up Jacket",
        "description": "Lightweight zip up jacket for layering during cool weather.",
        "price": 59.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 105,
    },
    {
        "external_id": 65,
        "title": "Relaxed Cargo Pants",
        "description": "Comfortable cargo pants with multiple pockets and a relaxed fit.",
        "price": 52.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 143,
    },
    {
        "external_id": 66,
        "title": "Knit Sweater",
        "description": "Warm knit sweater with a soft texture for comfortable everyday layering.",
        "price": 48.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 132,
    },
    {
        "external_id": 67,
        "title": "Athletic Shorts",
        "description": "Lightweight athletic shorts with flexible fabric for workouts and running.",
        "price": 24.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1562886877-3c3e8f4c6f65?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 98,
    },
    {
        "external_id": 68,
        "title": "Linen Shirt",
        "description": "Breathable linen shirt suited for warm weather and relaxed occasions.",
        "price": 45.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 111,
    },
    {
        "external_id": 69,
        "title": "Classic Blazer",
        "description": "Tailored blazer that adds a polished look to formal and smart casual outfits.",
        "price": 99.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 174,
    },
    {
        "external_id": 70,
        "title": "Basic Tank Top",
        "description": "Soft lightweight tank top for casual outfits workouts and warm days.",
        "price": 17.99,
        "category": "Clothing",
        "image": "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 84,
    },
    {
        "external_id": 71,
        "title": "Running Cap",
        "description": "Lightweight breathable cap designed for running and outdoor activities.",
        "price": 18.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 116,
    },
    {
        "external_id": 72,
        "title": "Leather Belt",
        "description": "Classic leather belt with a simple buckle for everyday outfits.",
        "price": 27.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 125,
    },
    {
        "external_id": 73,
        "title": "Classic Backpack",
        "description": "Roomy everyday backpack with padded storage for books and a laptop.",
        "price": 49.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 164,
    },
    {
        "external_id": 74,
        "title": "Card Holder",
        "description": "Slim card holder designed for carrying essential cards in a compact format.",
        "price": 16.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 71,
    },
    {
        "external_id": 75,
        "title": "Canvas Tote Bag",
        "description": "Reusable canvas tote bag with sturdy handles for daily shopping and errands.",
        "price": 19.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 92,
    },
    {
        "external_id": 76,
        "title": "Travel Neck Pillow",
        "description": "Soft supportive neck pillow for comfortable travel and long journeys.",
        "price": 22.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1530441687753-cc7c6b9c7a8f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 65,
    },
    {
        "external_id": 77,
        "title": "Beanie Cap",
        "description": "Soft knit beanie for keeping warm during cooler weather.",
        "price": 15.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 78,
    },
    {
        "external_id": 78,
        "title": "Classic Analog Watch",
        "description": "Elegant analog watch with a clean dial and versatile everyday styling.",
        "price": 74.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 143,
    },
    {
        "external_id": 79,
        "title": "Travel Sunglasses Case",
        "description": "Protective hard case for storing sunglasses safely while traveling.",
        "price": 13.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 59,
    },
    {
        "external_id": 80,
        "title": "Compact Umbrella",
        "description": "Lightweight foldable umbrella that fits easily inside a backpack.",
        "price": 21.99,
        "category": "Accessories",
        "image": "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 87,
    },
    {
        "external_id": 81,
        "title": "Non Stick Frying Pan",
        "description": "Durable non stick frying pan for convenient everyday cooking.",
        "price": 32.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 176,
    },
    {
        "external_id": 82,
        "title": "Electric Kettle",
        "description": "Fast boiling electric kettle with a simple compact design.",
        "price": 39.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1594213114663-d94db9b171b9?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 203,
    },
    {
        "external_id": 83,
        "title": "French Press",
        "description": "Glass French press for making rich freshly brewed coffee at home.",
        "price": 26.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 189,
    },
    {
        "external_id": 84,
        "title": "Bamboo Cutting Board",
        "description": "Sturdy bamboo cutting board for everyday kitchen preparation.",
        "price": 24.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 98,
    },
    {
        "external_id": 85,
        "title": "Kitchen Knife Set",
        "description": "Practical kitchen knife set for slicing chopping and everyday food preparation.",
        "price": 49.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 154,
    },
    {
        "external_id": 86,
        "title": "Cotton Cushion Set",
        "description": "Soft decorative cushion covers that add comfort and style to living spaces.",
        "price": 29.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 76,
    },
    {
        "external_id": 87,
        "title": "Scented Candle",
        "description": "Pleasantly scented candle designed to create a warm relaxing atmosphere.",
        "price": 17.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 217,
    },
    {
        "external_id": 88,
        "title": "Laundry Basket",
        "description": "Lightweight laundry basket with handles for convenient home organization.",
        "price": 27.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1610557892470-a5d4c8c9e3e7?auto=format&fit=crop&w=600&q=80",
        "rating": 4.1,
        "rating_count": 68,
    },
    {
        "external_id": 89,
        "title": "Bathroom Organizer",
        "description": "Compact organizer for keeping toiletries and bathroom essentials neatly arranged.",
        "price": 20.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 82,
    },
    {
        "external_id": 90,
        "title": "Memory Foam Pillow",
        "description": "Supportive memory foam pillow designed for comfortable everyday sleep.",
        "price": 35.99,
        "category": "Home & Kitchen",
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 146,
    },
    {
        "external_id": 91,
        "title": "Makeup Brush Set",
        "description": "Complete makeup brush set with soft bristles for everyday beauty routines.",
        "price": 24.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 173,
    },
    {
        "external_id": 92,
        "title": "Gentle Face Cleanser",
        "description": "Gentle daily cleanser designed to remove impurities without feeling harsh.",
        "price": 15.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 139,
    },
    {
        "external_id": 93,
        "title": "Body Lotion",
        "description": "Lightweight body lotion that helps keep skin feeling smooth and moisturized.",
        "price": 14.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 102,
    },
    {
        "external_id": 94,
        "title": "Hair Care Shampoo",
        "description": "Everyday shampoo designed for a fresh clean hair care routine.",
        "price": 17.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
        "rating": 4.2,
        "rating_count": 95,
    },
    {
        "external_id": 95,
        "title": "Hair Conditioner",
        "description": "Moisturizing conditioner designed to leave hair feeling soft and manageable.",
        "price": 18.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 88,
    },
    {
        "external_id": 96,
        "title": "Hand Cream",
        "description": "Nourishing hand cream for keeping hands soft and comfortable throughout the day.",
        "price": 9.99,
        "category": "Beauty",
        "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 79,
    },
    {
        "external_id": 97,
        "title": "Study Highlighter Set",
        "description": "Bright smooth highlighters for study notes planning and organization.",
        "price": 9.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80",
        "rating": 4.5,
        "rating_count": 116,
    },
    {
        "external_id": 98,
        "title": "A4 Sketchbook",
        "description": "High quality sketchbook suitable for drawing illustration and creative practice.",
        "price": 18.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
        "rating": 4.6,
        "rating_count": 94,
    },
    {
        "external_id": 99,
        "title": "Sticky Notes Pack",
        "description": "Colorful sticky notes for reminders study organization and quick messages.",
        "price": 7.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1586282391129-76a6df230234?auto=format&fit=crop&w=600&q=80",
        "rating": 4.3,
        "rating_count": 73,
    },
    {
        "external_id": 100,
        "title": "Study Desk Pad",
        "description": "Large desk pad that provides a comfortable writing and study surface.",
        "price": 21.99,
        "category": "Stationery",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=600&q=80",
        "rating": 4.4,
        "rating_count": 91,
    },
]


for item in products:
    category, _ = Category.objects.get_or_create(
        name=item["category"]
    )

    Product.objects.update_or_create(
        external_id=item["external_id"],
        defaults={
            "title": item["title"],
            "description": item["description"],
            "price": item["price"],
            "category": category,
            "image": item["image"],
            "rating": item["rating"],
            "rating_count": item["rating_count"],
        },
    )


print(f"Successfully added {len(products)} products.")
